version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/data:/var/lib/postgresql/data
  backend:
    env_file: .env
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
