version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - data:/var/lib/postgresql
  backend:
    image: epitechregistry.azurecr.io/time-manager--backend:latest
    restart: unless-stopped
    env_file: .env
    domainname: "timemanagerepitechstudents"
    ports:
      - 4000:4000
    depends_on:
      - postgres
volumes:
  data:
    driver: azure_file
    driver_opts:
      share_name: timemanagerepitechstudents-volume
      storage_account_name: epitechstorageaccount
