version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/data:/var/lib/postgresql/data
  backend:
    restart: unless-stopped
    env_file: .env.production
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${CONTAINER_PORT}:${CONTAINER_PORT}
    depends_on:
      - postgres
