version: "3.7"
services:
  backend:
    image: epitechregistry.azurecr.io/time-manager--backend:latest
    restart: unless-stopped
    env_file:
      - .env.production
    domainname: "timemanagerepitechstudents"
    ports:
      - 4000:4000
