# APPLICATION ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
data:
  container_port: "80"
  ssl_enabled: "1"
---
# APPLICATION ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: application-secrets
data:
  secret_key_base: Um80M29XY1M5OXUvWnYrMVlFWXQvTU54eDlwcklsTU9leWhJdjJTMHluNjBoRmRDUG5ZMi9MT1YzNFR1QmczMg==
  database_url: ZWN0bzovL3Bvc3RncmVzOnJ1bjMxNDtyYWJiaXRAZXBpdGVjaC1wb3N0Z3Jlcy5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20vdGltZV9tYW5hZ2Vy
---
# APPLICATION DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-manager
  labels:
    tier: application
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      tier: application
  template:
    metadata:
      labels:
        tier: application
    spec:
      containers:
        - name: application
          image: epitechregistry.azurecr.io/time-manager--backend:latest
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: database_url
            - name: CONTAINER_PORT
              valueFrom:
                configMapKeyRef:
                  name: application-configmap
                  key: container_port
            - name: SSL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: application-configmap
                  key: ssl_enabled
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: epitech-cluster-secret
---
# APPLICATION SERVICES
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    tier: application
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
