# AZURE PRODUCTION STORAGE CLASS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-storage
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  protocol: nfs
mountOptions:
  - nconnect=8
---
# DATABASE ENV (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database-secrets
data:
  postgres_password: cnVuMzE0O3JhYmJpdA==
  postgres_user: cG9zdGdyZXM=
  postgres_db: dGltZV9tYW5hZ2Vy
---
# STATEFULSET
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    tier: database
spec:
  serviceName: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        tier: database
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: postgres_db
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/postgresql/data
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: database
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: azure-storage
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 10Gi
---
# INTERNAL SERVICES forward traffic to database on port 5432 using postgres hostname internally
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    tier: database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
---

